# Copyright © 2026 Michael Shields
# SPDX-License-Identifier: MIT

name: Test
on: [push, pull_request]

jobs:
  test-script:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - run: ./test/test.sh
